### ISSUE TITLE
How to see terminal details in email

### ISSUE THREAD

**Issue by 4spen** [zefy/lp-express-shipping-method-for-woocommerce#10]
How to see more delivery details (chosen terminal address/name) in emails for admin and user? 
Currently you can see these chosen terminal details in order details page.

**Comment by zefy** [comment]
If you are using default WooCommerce email template then everything should be fine.
If you have your own email template it must have `do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email );` line.

Quote from WooCommerce admin page:
> To override and edit this email template copy woocommerce/templates/emails/admin-new-order.php to your theme folder: <YOUR_TEMPLATE_NAME>/woocommerce/emails/admin-new-order.php.

**Comment by 4spen** [comment]
Thank you for info, made adjustments, all looking good!
