### ISSUE TITLE
undefined method WC_Order::get_id() with 

### ISSUE THREAD

**Issue by lapkritinis** [zefy/lp-express-shipping-method-for-woocommerce#5]
On a customer website there is older Woocommerce plugin 2.6.14 and on checkout it throws error:
<h1>Error thrown</h1><p>Call to undefined method WC_Order::get_id()</p>

**Comment by nerjok** [comment]
try to get id in an older way order->id or so.

**Comment by zefy** [comment]
Sorry, but there was no intention to support old WooCommerce/Wordpress versions.

But as @nerjok suggested, you can make changes yourself 🙂

**Comment by lapkritinis** [comment]
I propose fix: #6
